# Callback types
IDLE = 'IDLE'
START = 'START'
STOP = 'STOP'

DEFAULT_CALLBACK_EXCESSIVE_BLOCK_TIME = 0.5
MAX_CALLBACK_EXCESSIVE_BLOCK_TIME = 10.0

MIN_POOL_MONITOR_INTERVAL = 1.0

MIN_THREAD_LAUNCHER_TIMEOUT = 5.0

DEFAULT_WORKER_COUNT = 5

# States for TimedThread
CANCELLED = 'CANCELLED'
COMPLETED = 'COMPLETED'
INITIALIZED = 'INITIALIZED'
RUNNING = 'RUNNING'

# States that .cancel() returns False for
NOCANCELSTATES = ()

# Types for ThreadPoolWrapper
FUTURE = 'FUTURE'
THREAD = 'THREAD'
